# I use this file to test the function

In [2]:
from graphics import * 
import numpy as np

BOX_WIDTH = 50
NUM_COLUMN = 15
NUM_ROW = 15
CHESS_RADIUS = 20
CONNECT_N = 5

In [24]:
matrix = np.zeros((NUM_ROW, NUM_COLUMN), dtype=int)
list = [[1,0],[1,1], [1,2], [1,3],[1,4]]

for row, col in list:
    matrix[row, col] = 1
matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
matrix.T

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
weights = np.array([2**i for i in range(NUM_ROW)])
win_values = [sum(weights[i:i+CONNECT_N]) for i in range(len(weights) - CONNECT_N + 1)]

In [18]:
weights

array([    1,     2,     4,     8,    16,    32,    64,   128,   256,
         512,  1024,  2048,  4096,  8192, 16384])

In [19]:
win_values

[31, 62, 124, 248, 496, 992, 1984, 3968, 7936, 15872, 31744]

In [31]:
matrix_result = np.dot(matrix, weights)

In [32]:
if any(value in win_values for value in matrix_result):
    print("YES")

YES


In [2]:
import numpy as np

def rotateMatrix(matrix):
    n = matrix.shape[0] 
    max_length = 2 * n - 1  
    diagonal_matrix = []

    for offset in range(-n + 1, n):
        diag = matrix.diagonal(offset=offset)
        padding = [0] * (max_length - len(diag))
        padded_diag = padding[:len(padding)//2] + list(diag) + padding[len(padding)//2:]
        diagonal_matrix.append(padded_diag)


    for offset in range(-n + 1, n):
        diag = np.fliplr(matrix).diagonal(offset=offset)
        padding = [0] * (max_length - len(diag))
        padded_diag = padding[:len(padding)//2] + list(diag) + padding[len(padding)//2:]
        diagonal_matrix.append(padded_diag)

    return np.array(diagonal_matrix)

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

rotated_diagonals = rotateMatrix(matrix)
print("Rotated Diagonal Matrix:")
print(rotated_diagonals)


Rotated Diagonal Matrix:
[[ 0  0  0 13  0  0  0]
 [ 0  0  9 14  0  0  0]
 [ 0  0  5 10 15  0  0]
 [ 0  1  6 11 16  0  0]
 [ 0  0  2  7 12  0  0]
 [ 0  0  3  8  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0 16  0  0  0]
 [ 0  0 12 15  0  0  0]
 [ 0  0  8 11 14  0  0]
 [ 0  4  7 10 13  0  0]
 [ 0  0  3  6  9  0  0]
 [ 0  0  2  5  0  0  0]
 [ 0  0  0  1  0  0  0]]


In [1]:
a = [1,2,3,4,7]

In [2]:
a.append(3)

In [3]:
a[-1]

3

In [4]:
import numpy as np
board_rows = 15  
board_cols = 15

directions = [
        (1, 0), ## check from (0,3) to (0,4), (3,5)
        (0, 1), ## check from 
        (1, 1), ## check from (3,3) to (4,4), (5,5)
        (1, -1) ## check from (3,3) to (2,4), (3,5)
    ]

my_list = [(1,4),(0,2), (4,1)]
m = my_list[1][0]
n = my_list[1][1]
enemy_list =  []

In [6]:
eval_score = {
    (0,0,0,1,0,0): 20,
    (0,0,1,0,0,0): 20,
    (0,0,1,0,1,0): 120,
    (0,1,0,1,0,0): 120,
    (0,0,1,1,0,0): 120,
    (1,1,1,0,1): 720,
    (1,0,1,1,1): 720,
    (1,1,0,1,1): 720,
    (0,1,1,1,1): 720,
    (1,1,1,1,0): 720,
    (0,1,0,1,1,0): 720,
    (0,1,1,0,1,0): 720,
    (0,0,1,1,1,0): 720,
    (0,1,1,1,0,0): 720, 
    (0,1,1,1,1,0): 4320,
    (1,1,1,1,1): 50000
}

In [10]:

my_list = [(5,5), (5,6)]
enemy_list = []
m = my_list[1][0]
n = my_list[1][1]

out_of_board_positions = ([(i, -1) for i in range(-1, 16)] + 
                          [(-1, i) for i in range(-1, 16)] +
                          [(i, 16) for i in range(-1, 16)] +
                          [(16, i) for i in range(-1, 16)])

cur_score = 0
cur_shape = ()
for x_directions, y_directions in directions:    
    matrix_fiv = []
    matrix_six = []
    
    max_score = 0           ## max score in one direction
    new_shape = ()          ## new shape for max score
    for offset in range(-5, 1):
        pos = []
        
        for i in range(0, 6):
            row = m + (i + offset) * x_directions
            col = n + (i + offset) * y_directions
            current_position = (row, col)
            # 检查当前计算的行和列是否在棋盘范围内
            if current_position in out_of_board_positions:    
                pos.append(-1)
            else:
                if current_position in enemy_list:
                    pos.append(2)
                elif current_position in my_list:
                    pos.append(1)
                else:
                    pos.append(0)
            
        check_fiv = (pos[0], pos[1], pos[2], pos[3], pos[4])
        check_six = (pos[0], pos[1], pos[2], pos[3], pos[4], pos[5])
        matrix_fiv.append(check_fiv)
        matrix_six.append(check_six)
        
        
        for shape in eval_score:
            
            score = eval_score[shape]
            for i in range(len(matrix_fiv)):
                if i < len(matrix_six):
                    if matrix_fiv[i] == shape or matrix_six[i] == shape:         
                        if score > max_score:
                            max_score = score
                            new_shape = shape
                else:
                    if matrix_fiv[i] == shape:
                        if score > max_score:
                            max_score = score  
                            new_shape = shape
                            
    ## calculate if two shape intersect at one point
    ## than add the score together
    print(f"Max score in direction {x_directions, y_directions}: {max_score}")
    print(f"Max shape in direction {x_directions, y_directions}: {new_shape}")
    if max_score != 0:
        cur_score = max_score + cur_score
            
    
    print(matrix_six)

print(f"current score at this point: {cur_score}")

Max score in direction (1, 0): 20
Max shape in direction (1, 0): (0, 0, 0, 1, 0, 0)
[(0, 0, 0, 0, 0, 1), (0, 0, 0, 0, 1, 0), (0, 0, 0, 1, 0, 0), (0, 0, 1, 0, 0, 0), (0, 1, 0, 0, 0, 0), (1, 0, 0, 0, 0, 0)]
Max score in direction (0, 1): 120
Max shape in direction (0, 1): (0, 0, 1, 1, 0, 0)
[(0, 0, 0, 0, 1, 1), (0, 0, 0, 1, 1, 0), (0, 0, 1, 1, 0, 0), (0, 1, 1, 0, 0, 0), (1, 1, 0, 0, 0, 0), (1, 0, 0, 0, 0, 0)]
Max score in direction (1, 1): 20
Max shape in direction (1, 1): (0, 0, 0, 1, 0, 0)
[(0, 0, 0, 0, 0, 1), (0, 0, 0, 0, 1, 0), (0, 0, 0, 1, 0, 0), (0, 0, 1, 0, 0, 0), (0, 1, 0, 0, 0, 0), (1, 0, 0, 0, 0, 0)]
Max score in direction (1, -1): 20
Max shape in direction (1, -1): (0, 0, 0, 1, 0, 0)
[(0, 0, 0, 0, 0, 1), (0, 0, 0, 0, 1, 0), (0, 0, 0, 1, 0, 0), (0, 0, 1, 0, 0, 0), (0, 1, 0, 0, 0, 0), (1, 0, 0, 0, 0, 0)]
current score at this point: 180


In [8]:
## list 1 = my list
def find_score(list1, list2):
    directions = [
        (1, 0), ## check from (0,3) to (0,4), (3,5)
        (0, 1), ## check from 
        (1, 1), ## check from (3,3) to (4,4), (5,5)
        (1, -1) ## check from (3,3) to (2,4), (3,5)
    ]

    total_score = 0             ## total score in the whole list

    out_of_board_positions = ([(i, -1) for i in range(-1, 16)] + 
                                    [(-1, i) for i in range(-1, 16)] +
                                    [(i, 16) for i in range(-1, 16)] +
                                    [(16, i) for i in range(-1, 16)])
    check_exist = []
    for point in list1:
        m = point[0]
        n = point[1]
        cur_score = 0           ## score at one point in 4 directions
        already_scored = []
        score_shape = (0, None)
        for x_directions, y_directions in directions: 
            ## check if this shape is duplicate
            ## eg. [(2,3), (2,4)]
            ## (2,3) will have [(2,1), (2,2), (2,3), (2,4), (2,5), (2,6)], which is (0,0,1,1,0,0)
            ## (2,4) will also iterate the above
            ## so there is a duplicate
            
            is_duplicate = False
            
            for item in check_exist:
                for pt in item[2]:
                    if m == pt[0] and n == pt[1] and x_directions == item[0][0] and y_directions == item[0][1]:
                        is_duplicate = True
                        break
                if is_duplicate:
                    break
            if is_duplicate:
                continue        
                
            matrix_fiv = []
            matrix_six = []
            
            max_score = 0           ## score at one point in one direction
            new_shape = []          ## new shape for max score
            

            
            
            ## consider point = (2,3) in direction (1,0)
            ## ① [(2,-2), (2,-1), (2,0), (2,1), (2,2), (2,3)] => (-1,-1,0,0,0,1)
            ## ② [(2,-1), (2,0), (2,1), (2,2), (2,3), (2,4)]  => (-1,0,0,0,1,0)
            ## ③ [(2,0), (2,1), (2,2), (2,3), (2,4), (2,5)]   => (0,0,0,1,0,0)
            ## ④ [(2,1), (2,2), (2,3), (2,4), (2,5), (2,6)]   => (0,0,1,0,0,0)
            ## ⑤ [(2,2), (2,3), (2,4), (2,5), (2,6), (2,7)]   => (0,1,0,0,0,0)
            ## ⑥ [(2,3), (2,4), (2,5), (2,6), (2,8), (2,9)]   => (1,0,0,0,0,0)
            ## in this case, ③ and ④ score 20 each
            ## but we only take the max at one direction which is 20
            for offset in range(-5, 1):
                check = []
                matrix_pos = []
                for i in range(0, 6):
                    row = m + (i + offset) * x_directions
                    col = n + (i + offset) * y_directions                    
                    current_position = (row, col)
                    
                    ## if out of board, append -1
                    if current_position in out_of_board_positions:    
                        check.append(-1)
                    else:
                        if current_position in list2:
                            check.append(2)
                        elif current_position in list1:
                            check.append(1)
                        else:
                            check.append(0)
                    matrix_pos.append(current_position)
                iteration = (matrix_pos[0], matrix_pos[1], matrix_pos[2], matrix_pos[3], matrix_pos[4], matrix_pos[5])

                ## put them in a tuple
                check_fiv = (check[0], check[1], check[2], check[3], check[4])
                check_six = (check[0], check[1], check[2], check[3], check[4], check[5])
                
                ## put them into a matrix
                matrix_fiv.append(check_fiv)
                matrix_six.append(check_six)
                for shape in eval_score:
                    
                    score = eval_score[shape]
                    for i in range(len(matrix_fiv)):
                        if i < len(matrix_six):
                            if matrix_fiv[i] == shape or matrix_six[i] == shape:         
                                if score > max_score:
                                    max_score = score
                                    new_shape.append(shape)
                                    
                                    score_shape = ((x_directions, y_directions), score, iteration)
                        else:
                            if matrix_fiv[i] == shape:
                                if score > max_score:
                                    max_score = score  
                                    new_shape.append(shape)      
                                    score_shape = ((x_directions, y_directions), score, iteration)
            ## calculate if two shape intersect at one point
            ## than add the score together
            print(f"Max score in direction {x_directions, y_directions}: {max_score}")
            ## print(f"Max shape in direction {x_directions, y_directions}: {new_shape}")
            if max_score != 0:
                cur_score = max_score + cur_score
                ## print(score_shape)        
                check_exist.append(score_shape)
            ## print(matrix_six)
        print(check_exist)
        print(f"current score at this point {point}: {cur_score}")
            
        total_score = total_score + cur_score
    print(total_score)
    return total_score

In [9]:
my_list = [(5,5), (5,6)]
enemy_list = []

find_score(my_list, enemy_list)

Max score in direction (1, 0): 20
Max score in direction (0, 1): 120
Max score in direction (1, 1): 20
Max score in direction (1, -1): 20
[((1, 0), 20, ((2, 5), (3, 5), (4, 5), (5, 5), (6, 5), (7, 5))), ((0, 1), 120, ((5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8))), ((1, 1), 20, ((2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7))), ((1, -1), 20, ((2, 8), (3, 7), (4, 6), (5, 5), (6, 4), (7, 3)))]
current score at this point (5, 5): 180
Max score in direction (1, 0): 20
Max score in direction (1, 1): 20
Max score in direction (1, -1): 20
[((1, 0), 20, ((2, 5), (3, 5), (4, 5), (5, 5), (6, 5), (7, 5))), ((0, 1), 120, ((5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8))), ((1, 1), 20, ((2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7))), ((1, -1), 20, ((2, 8), (3, 7), (4, 6), (5, 5), (6, 4), (7, 3))), ((1, 0), 20, ((2, 6), (3, 6), (4, 6), (5, 6), (6, 6), (7, 6))), ((1, 1), 20, ((2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8))), ((1, -1), 20, ((2, 9), (3, 8), (4, 7), (5, 6), (6, 5), (7, 4)))]
current 