# I use this file to test the function

In [2]:
from graphics import * 
import numpy as np

BOX_WIDTH = 50
NUM_COLUMN = 15
NUM_ROW = 15
CHESS_RADIUS = 20
CONNECT_N = 5

In [24]:
matrix = np.zeros((NUM_ROW, NUM_COLUMN), dtype=int)
list = [[1,0],[1,1], [1,2], [1,3],[1,4]]

for row, col in list:
    matrix[row, col] = 1
matrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
matrix.T

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
weights = np.array([2**i for i in range(NUM_ROW)])
win_values = [sum(weights[i:i+CONNECT_N]) for i in range(len(weights) - CONNECT_N + 1)]

In [18]:
weights

array([    1,     2,     4,     8,    16,    32,    64,   128,   256,
         512,  1024,  2048,  4096,  8192, 16384])

In [19]:
win_values

[31, 62, 124, 248, 496, 992, 1984, 3968, 7936, 15872, 31744]

In [31]:
matrix_result = np.dot(matrix, weights)

In [32]:
if any(value in win_values for value in matrix_result):
    print("YES")

YES


In [2]:
import numpy as np

def rotateMatrix(matrix):
    n = matrix.shape[0] 
    max_length = 2 * n - 1  
    diagonal_matrix = []

    for offset in range(-n + 1, n):
        diag = matrix.diagonal(offset=offset)
        padding = [0] * (max_length - len(diag))
        padded_diag = padding[:len(padding)//2] + list(diag) + padding[len(padding)//2:]
        diagonal_matrix.append(padded_diag)


    for offset in range(-n + 1, n):
        diag = np.fliplr(matrix).diagonal(offset=offset)
        padding = [0] * (max_length - len(diag))
        padded_diag = padding[:len(padding)//2] + list(diag) + padding[len(padding)//2:]
        diagonal_matrix.append(padded_diag)

    return np.array(diagonal_matrix)

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

rotated_diagonals = rotateMatrix(matrix)
print("Rotated Diagonal Matrix:")
print(rotated_diagonals)


Rotated Diagonal Matrix:
[[ 0  0  0 13  0  0  0]
 [ 0  0  9 14  0  0  0]
 [ 0  0  5 10 15  0  0]
 [ 0  1  6 11 16  0  0]
 [ 0  0  2  7 12  0  0]
 [ 0  0  3  8  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0 16  0  0  0]
 [ 0  0 12 15  0  0  0]
 [ 0  0  8 11 14  0  0]
 [ 0  4  7 10 13  0  0]
 [ 0  0  3  6  9  0  0]
 [ 0  0  2  5  0  0  0]
 [ 0  0  0  1  0  0  0]]


In [1]:
a = [1,2,3,4,7]

In [2]:
a.append(3)

In [3]:
a[-1]

3

In [ ]:
board_history = [1,2,3]

In [1]:
board_history = board_history[:-2]

yes
